version: "3.9"

services:
  backend:
    build: ./backend
    container_name: killerbee-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env   # 👈 tells Docker to load your .env file
    environment:
      DB_HOST: db        # 👈 override DB_HOST to point to the container
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: killerbee-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
